name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ou a branch que você usa como principal

jobs:
  build-and-deploy:
    permissions:
      contents: write # Adiciona permissão de escrita para o GITHUB_TOKEN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false # Ignora explicitamente os submódulos

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use uma versão LTS do Node.js

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist